---
- name: Create virtual hosts For Mqtt
  rabbitmq_vhost:
      name: "{{ item }}"
      tracing: no
      state: present
  with_items:
     - tv_dev





- name: configure admin user for rabbitmq
  rabbitmq_user:
    user: longest_username_possible_for_admin
    password: saqweveU2dzPlhPBcBMciujhyt
    vhost: "{{ item }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    update_password: always
    tags: administrator
    state: present
  with_items:
        - /
        - tv_dev

- name: delete guest user
  rabbitmq_user:
    user: "guest"
    state: absent
# - name: Create virtual hosts For Mqtt
#   rabbitmq_vhost:
#       name: "{{ item }}"
#       tracing: no
#       state: present
#   with_items:
#      - tv_dev
#      - tv_prod
- name: Create User For Mqtt
  rabbitmq_user:
     user: "{{ item.user }}"
     password: "{{ item.passwd }}"
     vhost: "{{ item.vhost }}"
     configure_priv: .*
     tags: natco
     read_priv: ""
     write_priv: "amq.topic"
     state: present
  with_items:
        - { user: natco_gdc, passwd: iouyttt4rg97Xyjj8XMtFQD8pmejhgvbf, vhost: tv_dev }
- name: Create Queue For Mqtt
  rabbitmq_queue:
        name: "{{ item.name }}"
        durable: true
        vhost: "{{ item.vhost }}"
        login_user: longest_username_possible_for_admin
        login_password: saqweveU2dzPlhPBcBMciujhyt
        auto_delete: no
        state: present
  with_items:
         - { name: tv_natco_gdc_event,  vhost: tv_dev}
         - { name: tv_natco_gdc_performance,  vhost: tv_dev}
- name: Create binding For Mqtt
  rabbitmq_binding:
        name: "{{ item.exchange_name }}"
        destination_type: queue
        destination: "{{ item.queue_name }}"
        vhost: "{{ item.vhost }}"
        login_user: longest_username_possible_for_admin
        login_password: saqweveU2dzPlhPBcBMciujhyt
        routing_key: "{{ item.key }}"
        state: present
  with_items:
         - { exchange_name: amq.topic, queue_name: tv_natco_gdc_event, vhost: tv_dev, key: tv.natco.gdc.event }
         - { exchange_name: amq.topic, queue_name: tv_natco_gdc_performance, vhost: tv_dev, key: tv.natco.gdc.performance }
- name: Create HA set_policy
  rabbitmq_policy:
        name: "{{ item.name }}"
        pattern: .*
        apply_to: all
        state: present
        vhost: "{{ item.vhost }}"
  args:
      tags:
        ha-mode: all
        ha-sync-mode: automatic
  with_items:
        - { name: head, vhost: / }
        - { name: gdc,   vhost: tv_dev }
