---
- name: ensure certain directories exists
  file:
    owner: root
    group: root
    path: "{{item}}"
    state: directory
    mode: 0755
    recurse: yes
  with_items:
    - /opt
    - /var/lib/kafka
    - /var/lib/zookeeper
- name: Ensure unzip package is installed
  apt:
    name: unzip
    state: present
    update_cache: yes
