- hosts: tvmariadbprod_dtdl
  roles:
    - { role: roles/mariadb-galera-cluster, tags: ["mariadb"] }
   # - { role: rsyslog_json, tags: ["rsyslogjson"] }
  #    - { role: zabbix_user_parameter, tags: ["redis_zabbix"]}
  become: True
