---
- name: Restart ZooKeeper service
  systemd:
    name: zookeeper.service
    state: restarted
    daemon_reload: yes
- name: Restart Kafka service
  systemd:
    name: kafka.service
    state: restarted
    daemon_reload: yes
