---
# tasks file for dt_rabbitmq
- name: Add package signing key for rabbitmq
  apt_key:
    keyserver: "hkps.pool.sks-keyservers.net"
    id: "0x6B73A36E6026DFCA"
    state: present
- name: Add erlang repository
  apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq-erlang/debian xenial erlang
      state: present # not required. choices: absent;present. A source string state.
      update_cache: yes # not required. Run the equivalent of C(apt-get update) when a change occurs.  Cache updates are run after making changes.
      filename: erlang # not required. Sets the name of the source list file in sources.list.d. Defaults to a file name based on the repository source url. The .list extension will be automatically added.

- name: Add rabbitmq repository
  apt_repository:
      repo: deb https://dl.bintray.com/rabbitmq/debian xenial main
      state: present # not required. choices: absent;present. A source string state.
      update_cache: yes # not required. Run the equivalent of C(apt-get update) when a change occurs.  Cache updates are run after making changes.
      filename: rabbitmq # not required. Sets the name of the source list file in sources.list.d. Defaults to a file name based on the repository source url. The .list extension will be automatically added.

- name: Install required packages
  apt:
      update_cache: yes # not required. Run the equivalent of C(apt-get update) before the operation. Can be run as part of the package installation or as a separate step.
      name: "{{item}}" # not required. A list of package names, like C(foo), or package specifier with version, like C(foo=1.0). Name wildcards (fnmatch) like C(apt*) and version wildcards like C(foo=1.0*) are also supported.
      state: present # not required. choices: absent;build-dep;latest;present. Indicates the desired package state. C(latest) ensures that the latest version is installed. C(build-dep) ensures the package build dependencies are installed.
  with_items:
    - rabbitmq-server
- name: Install base packages
  apt:
      name: "{{ item }}"
      state: installed
  with_items:
       - python-pip
       - curl


- name: Install Python dependency
  pip:
      name: requests
      state: latest
- name: Install rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_mqtt,rabbitmq_peer_discovery_aws,rabbitmq_web_mqtt
    state: enabled
- name: configure rabbmqconfig
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf

- name: configure rabbmqenvconfig
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf


- name: Copy Erlang  cookie
  template:
     src: erlang.cookie.j2
     dest: /var/lib/rabbitmq/.erlang.cookie
     owner: rabbitmq
     group: rabbitmq
     mode: '400'
     backup: yes
- name: Restart rabbitmq server
  service:
    name: rabbitmq-server
    state: restarted
