# - name: Add an apt key by id from a keyserver
#   apt_key:
#     keyserver: keyserver.ubuntu.com:80
#     id: 0xF1656F24C74CD1D8
# - name: Add an apt key by id from a keyserver
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- apt_repository:
    repo: deb [arch=amd64,i386,ppc64el] https://mirrors.gethosted.online/mariadb/repo/10.4/ubuntu xenial main
    state: present
    filename: mariadb.repo
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=31536000

- name: debian | installing pre-reqs
  apt:
    name:
      [
        "apt-transport-https",
        "software-properties-common",
        "python-mysqldb",
      ]
    state: "present"
  become: true
