- name: Add mongodb key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4
    state: present
- name : Add mongodb repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse"
    state: present
    filename: mongodb.list
- name: Install mongodb
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - mongodb-org=4.0.6
    - mongodb-org-server=4.0.6
    - mongodb-org-shell=4.0.6
    - mongodb-org-mongos=4.0.6
    - mongodb-org-tools=4.0.6
- name: prevent upgrade
  dpkg_selections:
    name: "{{item}}"
    selection: hold 
  with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-org-tools         
  
