- name: "configure systemd file for kafka"
  template:
    src: kafka.service.j2
    dest: "/etc/systemd/system/kafka.service"
  # notify:
  #   - Restart Kafka service
- name: Start the kafka service
  systemd:
    name: kafka.service
    state: started
    enabled: yes
    daemon_reload: yes
